import { createElement } from "react";
import { Icon as IconifyIcon } from "@iconify/react";

export const Icon = ({ icon, className = "", size = "1em", ...props }) =>
  createElement(IconifyIcon, { icon, className, width: size, height: size, ...props });

export const I = {
  overview: "mdi:chart-bar",
  repos: "mdi:folder",
  activity: "mdi:calendar-month",
  languages: "mdi:code-tags",
  ai: "mdi:robot",
  sun: "mdi:weather-sunny",
  moon: "mdi:weather-night",
  alert: "mdi:alert-circle-outline",
  warning: "mdi:alert",
  check: "mdi:check-circle",
  close: "mdi:close",
  refresh: "mdi:refresh",
  user: "mdi:account",
  users: "mdi:account-group",
  building: "mdi:office-building",
  calendar: "mdi:calendar",
  link: "mdi:link-variant",
  star: "mdi:star",
  fork: "mdi:source-fork",
  trophy: "mdi:trophy",
  chartBar: "mdi:chart-bar",
  chartLine: "mdi:chart-line",
  fire: "mdi:fire",
  package: "mdi:package-variant-closed",
  folderOpen: "mdi:folder-open",
  hammer: "mdi:hammer-wrench",
  rocket: "mdi:rocket-launch",
  fileDocument: "mdi:file-document",
  fileJson: "mdi:code-json",
  filePdf: "mdi:file-pdf-box",
  brain: "mdi:brain",
  briefcase: "mdi:briefcase",
  shield: "mdi:shield-check",
  armFlex: "mdi:arm-flex",
  diamond: "mdi:diamond",
  lightbulb: "mdi:lightbulb-on",
  target: "mdi:target",
  swordCross: "mdi:sword-cross",
  scale: "mdi:scale-balance",
  sparkles: "mdi:sparkles",
  party: "mdi:party-popper",
  shuffle: "mdi:shuffle-variant",
  globe: "mdi:web",
  magnify: "mdi:magnify",
  lightning: "mdi:lightning-bolt",
  alertOctagon: "mdi:alert-octagon",
  ban: "mdi:block-helper",
  information: "mdi:information-outline",
  loading: "mdi:loading",
  bug: "mdi:bug",
  clock: "mdi:clock-outline",
  chevronLeft: "mdi:chevron-left",
  chevronRight: "mdi:chevron-right",
  chevronDown: "mdi:chevron-down",
  crystalBall: "mdi:crystal-ball",
  hamburger: "mdi:menu",
  email: "mdi:email-outline",
  about: "mdi:information-outline",
  contact: "mdi:card-account-mail",
  linkedin: "mdi:linkedin",
  github: "mdi:github",
  web: "mdi:web",
};
