import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import {
  generateFilename,
  formatFileSize,
  formatDateForExport,
  formatNumber
} from './exportUtils';

const BRAND = {
  name: 'GitScope',
  tagline: 'Developer Profile Analytics',
  dark: [30, 41, 59],
  accent: [56, 189, 248],
  coverBg: [15, 23, 42],
  watermark: [30, 41, 59],
  barHeight: 7,
};

const fetchImageAsBase64 = async (url) => {
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const blob = await res.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
};

const COLORS = {
  primary: [103, 80, 164],
  onPrimary: [255, 255, 255],
  primaryContainer: [234, 221, 255],
  onPrimaryContainer: [33, 0, 93],
  secondaryContainer: [232, 222, 248],
  onSecondaryContainer: [29, 25, 43],
  tertiary: [125, 82, 96],
  surfaceContainer: [243, 237, 247],
  surfaceContainerLow: [231, 224, 236],
  background: [255, 251, 254],
  onBackground: [28, 27, 31],
  onSurfaceVariant: [73, 69, 79],
  outline: [121, 116, 126],
  error: [179, 38, 30],
};

const cleanText = (text) => {
  if (!text) return '';
  return text
    .replace(/[\u{1F600}-\u{1F9FF}]/gu, '')
    .replace(/[\u{2600}-\u{27BF}]/gu, '')
    .replace(/[^\u0020-\u007E]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
};

const drawSectionHeader = (pdf, margin, pageWidth, yPos, title) => {
  pdf.setFillColor(...COLORS.surfaceContainer);
  pdf.roundedRect(margin - 3, yPos - 3, pageWidth + 6, 12, 2, 2, 'F');
  pdf.setTextColor(...COLORS.onBackground);
  pdf.setFontSize(13);
  pdf.setFont('helvetica', 'bold');
  pdf.text(title, margin, yPos + 5);
  return yPos + 15;
};

const drawCoverPage = (pdf, data, isEnglish, logoLight) => {
  const cx = 105;
  const cy = 110;

  pdf.setFillColor(...BRAND.coverBg);
  pdf.rect(0, 0, 210, 297, 'F');

  pdf.setDrawColor(...BRAND.accent);
  pdf.setLineWidth(0.25);
  pdf.circle(170, 80, 70);
  pdf.setLineWidth(0.15);
  pdf.circle(170, 80, 58);
  pdf.circle(170, 80, 82);

  if (logoLight) {
    const imgWidth = 55;
    const imgHeight = 30;
    pdf.addImage(logoLight, 'PNG', cx - imgWidth / 2, 52, imgWidth, imgHeight);
  }

  pdf.setTextColor(203, 213, 225);
  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'italic');
  pdf.text(BRAND.tagline, cx, cy + 17, { align: 'center' });

  pdf.setDrawColor(...BRAND.accent);
  pdf.setLineWidth(0.5);
  pdf.line(cx - 38, cy + 32, cx + 38, cy + 32);
  pdf.setFillColor(...BRAND.accent);
  pdf.circle(cx, cy + 32, 1.5, 'F');

  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.text(cleanText(data.user.name || data.user.login), cx, cy + 65, { align: 'center' });

  pdf.setTextColor(203, 213, 225);
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`@${data.user.login}`, cx, cy + 82, { align: 'center' });

  pdf.setTextColor(148, 163, 184);
  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'normal');
  pdf.text(
    `${isEnglish ? 'Generated on' : 'Generado el'}: ${new Date().toLocaleDateString(isEnglish ? 'en-US' : 'es-ES')}`,
    cx, cy + 100, { align: 'center' }
  );

  const sx = 175;
  const sy = 260;
  pdf.setDrawColor(...BRAND.accent);
  pdf.setLineWidth(0.4);
  pdf.circle(sx, sy, 6);
  pdf.setLineWidth(0.3);
  pdf.circle(sx, sy, 12);
  pdf.setLineWidth(0.2);
  pdf.circle(sx, sy, 19);
  pdf.setLineWidth(0.15);
  pdf.line(sx - 22, sy, sx + 22, sy);
  pdf.line(sx, sy - 22, sx, sy + 22);
  pdf.setFillColor(...BRAND.accent);
  pdf.circle(sx, sy, 1.2, 'F');
};

const drawBrandBar = (pdf, logoDark) => {
  const barH = BRAND.barHeight;
  pdf.setFillColor(...BRAND.dark);
  pdf.rect(0, 0, 210, barH, 'F');

  if (logoDark) {
    pdf.addImage(logoDark, 'PNG', 8, 1, 5, 5);
  }

  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(6.5);
  pdf.setFont('helvetica', 'bold');
  pdf.text('GitScope', 14, 5);
};

const drawFooter = (pdf, margin, pageWidth, isEnglish, dateStr, pageNum, totalPages) => {
  pdf.setDrawColor(200, 200, 205);
  pdf.setLineWidth(0.3);
  pdf.line(margin, 283, margin + pageWidth, 283);

  pdf.setTextColor(...COLORS.onSurfaceVariant);
  pdf.setFontSize(6.5);
  pdf.setFont('helvetica', 'normal');
  const brandLine = isEnglish
    ? 'Generated by GitScope \u00B7 github-analytics-dashboard'
    : 'Generado por GitScope \u00B7 github-analytics-dashboard';
  pdf.text(brandLine, margin, 288);

  pdf.text(
    `${dateStr}  |  P\u00e1g ${pageNum}/${totalPages}`,
    margin + pageWidth, 288,
    { align: 'right' }
  );

  pdf.setFillColor(...BRAND.accent);
  pdf.circle(margin + pageWidth + 3, 288, 0.8, 'F');
};

const drawWatermark = (pdf) => {
  pdf.setTextColor(225, 225, 230);
  pdf.setFontSize(50);
  pdf.setFont('helvetica', 'bold');
  pdf.text('GitScope', 105, 150, { align: 'center', angle: -40 });
};

export const generatePDFReport = async (data, language = 'es') => {
  if (!data || !data.user) {
    throw new Error('No profile data available to export');
  }

  const [logoDark, logoLight] = await Promise.all([
    fetchImageAsBase64('/icons/light2.png'),
    fetchImageAsBase64('/icons/dark2.png'),
  ]);

  const isEnglish = language === 'en';
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = 190;
  const pageHeight = 277;
  const margin = 10;
  let yPos = margin + BRAND.barHeight;
  let xOffset;

  pdf.setProperties({
    title: `${isEnglish ? 'Profile' : 'Perfil'} de ${data.user.login} \u2014 GitScope`,
    author: 'GitScope Analytics',
    creator: 'GitScope Analytics',
    subject: isEnglish
      ? 'GitHub profile report generated by GitScope'
      : 'Reporte de perfil GitHub generado por GitScope',
    keywords: `github, analytics, profile, ${data.user.login}`,
  });

  const checkPageBreak = (neededHeight) => yPos + neededHeight > pageHeight;

  const newPage = () => {
    pdf.addPage();
    yPos = margin + BRAND.barHeight;
    drawBrandBar(pdf, logoDark);
  };

  drawCoverPage(pdf, data, isEnglish, logoLight);

  pdf.addPage();
  drawBrandBar(pdf, logoDark);

  pdf.setFillColor(...COLORS.primary);
  pdf.rect(0, BRAND.barHeight, 210, 35, 'F');

  pdf.setTextColor(...COLORS.onPrimary);
  pdf.setFontSize(22);
  pdf.setFont('helvetica', 'bold');
  pdf.text(cleanText(data.user.name || data.user.login), margin, BRAND.barHeight + 13);

  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  pdf.text(
    `@${data.user.login} | ${isEnglish ? 'GitHub Profile Report' : 'Informe de Perfil GitHub'}`,
    margin,
    BRAND.barHeight + 21
  );

  yPos = 45 + BRAND.barHeight;

  const stats = [
    {
      value: formatNumber(data.user.followers, language),
      label: isEnglish ? 'Followers' : 'Seguidores'
    },
    {
      value: formatNumber(data.user.following, language),
      label: isEnglish ? 'Following' : 'Siguiendo'
    },
    {
      value: formatNumber(data.user.public_repos, language),
      label: isEnglish ? 'Repos' : 'Repositorios'
    }
  ];

  xOffset = margin;
  stats.forEach(stat => {
    pdf.setFillColor(...COLORS.primaryContainer);
    pdf.roundedRect(xOffset, yPos, 56, 22, 3, 3, 'F');
    pdf.setTextColor(...COLORS.onPrimaryContainer);
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text(stat.value.toString(), xOffset + 28, yPos + 10, { align: 'center' });
    pdf.setTextColor(...COLORS.onSurfaceVariant);
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'normal');
    pdf.text(stat.label, xOffset + 28, yPos + 17, { align: 'center' });
    xOffset += 62;
  });
  yPos += 30;

  if (data.user.bio) {
    pdf.setTextColor(...COLORS.onBackground);
    pdf.setFontSize(10);
    const bioLines = pdf.splitTextToSize(cleanText(data.user.bio), pageWidth);
    pdf.text(bioLines, margin, yPos);
    yPos += bioLines.length * 5 + 5;
  }

  pdf.setTextColor(...COLORS.onSurfaceVariant);
  pdf.setFontSize(9);
  const metaParts = [];
  if (data.user.location) metaParts.push(`${isEnglish ? 'Location' : 'Ubicacion'}: ${cleanText(data.user.location)}`);
  if (data.user.company) metaParts.push(`${isEnglish ? 'Company' : 'Empresa'}: ${cleanText(data.user.company)}`);
  metaParts.push(
    `${isEnglish ? 'Joined' : 'Se unio'}: ${formatDateForExport(data.user.created_at, language)}`
  );
  pdf.text(metaParts.join('  |  '), margin, yPos);
  yPos += 15;

  if (checkPageBreak(80)) newPage();

  yPos = drawSectionHeader(
    pdf, margin, pageWidth, yPos,
    isEnglish ? 'Analytics Summary' : 'Resumen de Analisis'
  );

  const totalStars = (data.repos || []).reduce((sum, r) => sum + (r.stargazers_count || 0), 0);
  const totalForks = (data.repos || []).reduce((sum, r) => sum + (r.forks_count || 0), 0);
  const mainLanguage = data.analytics?.languages?.[0]?.name || '-';
  const totalCommits = (data.events || [])
    .filter(e => e.type === 'PushEvent')
    .reduce((sum, e) => sum + (e.payload?.commits?.length || 0), 0);

  const analyticsStats = [
    { value: formatNumber(totalStars, language), label: isEnglish ? 'Total Stars' : 'Estrellas' },
    { value: formatNumber(totalForks, language), label: isEnglish ? 'Total Forks' : 'Forks' },
    { value: formatNumber(data.repos?.length || 0, language), label: isEnglish ? 'Repositories' : 'Repos' },
    { value: mainLanguage, label: isEnglish ? 'Main Language' : 'Lenguaje ppal.' }
  ];

  xOffset = margin;
  analyticsStats.forEach((stat, i) => {
    if (i > 0 && i % 2 === 0) {
      xOffset = margin;
      yPos += 26;
    }

    pdf.setFillColor(...COLORS.secondaryContainer);
    pdf.roundedRect(xOffset, yPos, 90, 24, 3, 3, 'F');
    pdf.setTextColor(...COLORS.onSecondaryContainer);
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text(stat.value.toString(), xOffset + 45, yPos + 10, { align: 'center' });
    pdf.setTextColor(...COLORS.onSurfaceVariant);
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'normal');
    pdf.text(stat.label, xOffset + 45, yPos + 18, { align: 'center' });
    xOffset += 95;
  });
  yPos += 32;

  if (data.analytics?.insights?.length > 0) {
    if (checkPageBreak(50)) newPage();

    yPos = drawSectionHeader(
      pdf, margin, pageWidth, yPos,
      isEnglish ? 'Key Insights' : 'Perspectivas Clave'
    );

    const insights = data.analytics.insights.slice(0, 6);
    xOffset = margin;

    insights.forEach((insight, i) => {
      if (i > 0 && i % 2 === 0) {
        xOffset = margin;
        yPos += 22;
      }

      if (checkPageBreak(25)) {
        newPage();
        yPos = drawSectionHeader(
          pdf, margin, pageWidth, yPos,
          isEnglish ? 'Key Insights (cont.)' : 'Perspectivas Clave (cont.)'
        );
      }

      pdf.setFillColor(...COLORS.background);
      pdf.setDrawColor(...COLORS.outline);
      pdf.roundedRect(xOffset, yPos, 90, 20, 3, 3, 'FD');

      pdf.setTextColor(...COLORS.onBackground);
      pdf.setFontSize(9);
      pdf.setFont('helvetica', 'bold');

      const insightLabel = insight.titleKey
        ? cleanText(insight.titleKey.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase()))
        : '';
      const displayLabel = insightLabel.length > 14
        ? insightLabel.substring(0, 12) + '...'
        : insightLabel;

      pdf.text(displayLabel, xOffset + 5, yPos + 8);

      pdf.setTextColor(...COLORS.primary);
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'bold');
      pdf.text(
        cleanText(insight.value?.toString() || ''),
        xOffset + 85, yPos + 8,
        { align: 'right' }
      );

      pdf.setTextColor(...COLORS.onSurfaceVariant);
      pdf.setFontSize(7);
      pdf.setFont('helvetica', 'normal');
      pdf.text(
        cleanText(insight.description || ''),
        xOffset + 5, yPos + 15
      );

      xOffset += 95;
    });
    yPos += 26;
  }

  if (totalCommits > 0) {
    if (checkPageBreak(15)) newPage();

    pdf.setFillColor(...COLORS.primaryContainer);
    pdf.roundedRect(margin, yPos, pageWidth, 12, 3, 3, 'F');
    pdf.setTextColor(...COLORS.onPrimaryContainer);
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'bold');
    pdf.text(
      `${isEnglish ? 'Total Commits' : 'Total Commits'}: ${formatNumber(totalCommits, language)}  |  ${isEnglish ? 'Events' : 'Eventos'}: ${formatNumber(data.events?.length || 0, language)}`,
      margin + pageWidth / 2, yPos + 8,
      { align: 'center' }
    );
    yPos += 18;
  }

  if (checkPageBreak(60)) newPage();

  const topRepos = [...(data.repos || [])]
    .filter(r => r.stargazers_count > 0)
    .sort((a, b) => b.stargazers_count - a.stargazers_count)
    .slice(0, 8);

  if (topRepos.length > 0) {
    yPos = drawSectionHeader(
      pdf, margin, pageWidth, yPos,
      isEnglish ? 'Top Repositories' : 'Repositorios Destacados'
    );

    pdf.setFillColor(...COLORS.surfaceContainer);
    pdf.roundedRect(margin, yPos - 1, pageWidth, 10, 2, 2, 'F');
    pdf.setTextColor(...COLORS.onBackground);
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'bold');
    pdf.text(isEnglish ? 'Repository' : 'Repositorio', margin + 5, yPos + 6);
    pdf.text(isEnglish ? 'Stars' : 'Estrellas', margin + 140, yPos + 6, { align: 'right' });
    pdf.text(isEnglish ? 'Language' : 'Lenguaje', margin + 180, yPos + 6, { align: 'right' });
    yPos += 13;

    topRepos.forEach((repo, i) => {
      if (checkPageBreak(15)) {
        newPage();
        yPos = drawSectionHeader(
          pdf, margin, pageWidth, yPos,
          isEnglish ? 'Top Repositories (cont.)' : 'Repositorios Destacados (cont.)'
        );
      }

      const bgColor = i % 2 === 0 ? COLORS.surfaceContainerLow : [255, 255, 255];
      pdf.setFillColor(...bgColor);
      pdf.roundedRect(margin, yPos, pageWidth, 12, 2, 2, 'F');

      pdf.setTextColor(...COLORS.primary);
      pdf.setFontSize(9);
      pdf.setFont('helvetica', 'bold');
      const repoName = repo.name.length > 30 ? repo.name.substring(0, 28) + '...' : repo.name;
      pdf.text(`${i + 1}. ${cleanText(repoName)}`, margin + 3, yPos + 8);

      pdf.setTextColor(...COLORS.tertiary);
      pdf.setFontSize(9);
      pdf.text(formatNumber(repo.stargazers_count, language), margin + 140, yPos + 8, { align: 'right' });

      if (repo.language) {
        pdf.setTextColor(...COLORS.onSurfaceVariant);
        pdf.setFontSize(8);
        pdf.text(cleanText(repo.language), margin + 180, yPos + 8, { align: 'right' });
      }

      yPos += 14;
    });
    yPos += 8;
  }

  const topLangs = (data.analytics?.languages || []).slice(0, 8);
  if (topLangs.length > 0) {
    if (checkPageBreak(50)) newPage();

    yPos = drawSectionHeader(
      pdf, margin, pageWidth, yPos,
      isEnglish ? 'Top Languages' : 'Lenguajes Principales'
    );

    const maxLangCount = Math.max(...topLangs.map(l => l.count), 1);
    const barStartX = margin + 50;
    const barMaxWidth = 110;
    const countLabelX = barStartX + barMaxWidth + 5;

    topLangs.forEach((lang) => {
      if (checkPageBreak(14)) {
        newPage();
        yPos = drawSectionHeader(
          pdf, margin, pageWidth, yPos,
          isEnglish ? 'Top Languages (cont.)' : 'Lenguajes Principales (cont.)'
        );
      }

      pdf.setTextColor(...COLORS.onBackground);
      pdf.setFontSize(9);
      pdf.setFont('helvetica', 'bold');
      pdf.text(cleanText(lang.name), margin, yPos + 4);

      const barWidth = Math.max((lang.count / maxLangCount) * barMaxWidth, 4);
      pdf.setFillColor(...COLORS.surfaceContainerLow);
      pdf.roundedRect(barStartX, yPos, barMaxWidth, 8, 2, 2, 'F');
      pdf.setFillColor(...COLORS.primary);
      pdf.roundedRect(barStartX, yPos, barWidth, 8, 2, 2, 'F');

      pdf.setTextColor(...COLORS.onSurfaceVariant);
      pdf.setFontSize(8);
      pdf.setFont('helvetica', 'normal');
      pdf.text(
        `${lang.count} ${isEnglish ? 'repos' : 'repos'}`,
        countLabelX, yPos + 4
      );

      yPos += 12;
    });
    yPos += 8;
  }

  if (data.user.blog) {
    if (checkPageBreak(12)) newPage();
    pdf.setTextColor(...COLORS.onSurfaceVariant);
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'normal');
    pdf.text(
      `${isEnglish ? 'Website' : 'Sitio web'}: ${data.user.blog}`,
      margin, yPos
    );
    yPos += 8;
  }

  if (data.user.twitter_username) {
    pdf.setTextColor(...COLORS.onSurfaceVariant);
    pdf.setFontSize(8);
    pdf.text(
      `Twitter: @${data.user.twitter_username}`,
      margin, yPos
    );
    yPos += 8;
  }

  const pageCount = pdf.internal.getNumberOfPages();
  const dateStr = new Date().toLocaleDateString(isEnglish ? 'en-US' : 'es-ES');

  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);

    if (i === 1) {
      pdf.setTextColor(148, 163, 184);
      pdf.setFontSize(6);
      pdf.setFont('helvetica', 'normal');
      pdf.text('GitScope \u00B7 github-analytics-dashboard', 105, 290, { align: 'center' });
    } else {
      drawBrandBar(pdf, logoDark);
      drawFooter(pdf, margin, pageWidth, isEnglish, dateStr, i, pageCount);
      drawWatermark(pdf);
    }
  }

  const filename = generateFilename(`${data.user.login}_profile`, 'pdf');
  const pdfBlob = pdf.output('blob');
  const sizeKB = pdfBlob.size / 1024;

  return {
    pdf,
    filename,
    sizeKB,
    sizeFormatted: formatFileSize(sizeKB),
    pageCount
  };
};

export const exportToPDF = async (data, language = 'es') => {
  const result = await generatePDFReport(data, language);
  result.pdf.save(result.filename);
  return {
    filename: result.filename,
    sizeKB: result.sizeKB,
    sizeFormatted: result.sizeFormatted,
    pageCount: result.pageCount
  };
};

export const exportPDFReport = exportToPDF;

export const exportHTMLToPDF = async (element, filename) => {
  if (!element) {
    throw new Error('No element provided for PDF export');
  }

  try {
    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: '#FFFBFE'
    });

    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF({
      orientation: canvas.width > canvas.height ? 'l' : 'p',
      unit: 'px',
      format: [canvas.width, canvas.height]
    });

    pdf.addImage(imgData, 'PNG', 0, 0, canvas.width, canvas.height);
    pdf.save(filename);

    const pdfBlob = pdf.output('blob');
    const sizeKB = pdfBlob.size / 1024;

    return {
      filename,
      sizeKB,
      sizeFormatted: formatFileSize(sizeKB),
      pageCount: 1
    };
  } catch (err) {
    throw new Error(`Failed to generate PDF from HTML: ${err.message}`);
  }
};
